export const LANG_BR_NAME = 'br'; 
export const LANG_BR_TRANS = { 
  'USUÁRIO':'USUÁRIO', 
  'CONSULTAR':'CONSULTAR', 
  'Consultar':'Consultar', 
  'EDITAR':'EDITAR', 
  'INSERIR':'INSERIR', 
  'Relatórios':'Relatórios', 
  'Usuários':'Usuários', 
  'Cadastros':'Cadastros', 
  'RELATÓRIO':'RELATÓRIO', 
  'Itens':'Itens', 
  'apontamentos':'apontamentos', 
  'Permissões':'Permissões', 
  'Grupo de Usuários':'Grupo de Usuários', 
  'Administração':'Administração', 
  'Dicionário':'Dicionário', 
  'CÓDIGO':'CÓDIGO', 
 'GRUPO':'GRUPO', 
 'BEM VINDO AO SISTEMA':'BEM VINDO AO SISTEMA', 
 'é obrigatório':'é obrigatório', 
 'Relatório':'Relatório', 
 'RELATÓRIO DE':'RELATÓRIO DE', 
 'FILTRO RELATÓRIO':'FILTRO RELATÓRIOS', 
 'FILTRO APONTAMENTO':'FILTRO APONTAMENTO', 
  'cadastro de':'cadastro de', 
  'APONTAMENTO DE TEMPO':'APONTAMENTO DE TEMPO', 
  'Adicionar':'Adicionar',
  'Gravar':'Gravar',
  'Cancelar':'Cancelar',
  'Excluir':'Excluir', 
  'Editar':'Editar', 
  'CAMPOS':'CAMPOS', 
  'TOTAL GERAL':'TOTAL GERAL', 
  'Gráficos':'Gráficos', 
  'Imprimir':'Imprimir', 
  'Voltar':'Voltar', 
  'PIZZA':'PIZZA', 
  'LINHAS':'LINHAS', 
  'BARRAS':'BARRAS', 
  'DE':'DE', 
  'ATÉ':'ATÉ', 
  'ENTRAR':'ENTRAR', 
  'ACESSAR':'ACESSAR', 
  'LOGIN':'LOGIN', 
  'SENHA':'SENHA', 
 'Yumy Foods':'Yumy Foods', 
  'Ativo':'Ativo', 
  'Bonificação':'Bonificação', 
  'Bonificação por Compras':'Bonificação por Compras', 
  'Cardápio':'Cardápio', 
  'Cardapio':'Cardapio', 
  'Categoria':'Categoria', 
  'Categorias':'Categorias', 
  'Codigo':'Codigo', 
  'Código':'Código', 
  'Código de Bonificação':'Código de Bonificação', 
  'CheckList Pedidos':'CheckList Pedidos', 
  'Lista de Pedidos':'Lista de Pedidos', 
  'Complemento':'Complemento', 
  'Complemento do Endereço':'Complemento do Endereço', 
  'Data/Hora':'Data/Hora', 
  'Data e Hora do Pedido':'Data e Hora do Pedido', 
  'Data/Hora Entregue':'Data/Hora Entregue', 
  'Data/Hora que o pedido foi entregue':'Data/Hora que o pedido foi entregue', 
  'Data/Hora Retirado':'Data/Hora Retirado', 
  'Data/Hora que saiu para Entrega':'Data/Hora que saiu para Entrega', 
  'Descrição':'Descrição', 
  'Descrição do Prato':'Descrição do Prato', 
  'Estoque':'Estoque', 
  'Estoque do Produto':'Estoque do Produto', 
  'Fone':'Fone', 
  'Telefone de Contato':'Telefone de Contato', 
  'Forma Pgto.':'Forma Pgto.', 
  'Forma de Pagamento':'Forma de Pagamento', 
  'Imagem':'Imagem', 
  'Imagem do Prato':'Imagem do Prato', 
  'Informações Adicionais/Observações':'Informações Adicionais/Observações', 
  'Informações adicionas e Observações':'Informações adicionas e Observações', 
  //'Lista de Pedidos':'Lista de Pedidos', 
  'Número':'Número', 
  'Número(Endereço)':'Número(Endereço)', 
  'Nome':'Nome', 
  'Nome do Prato':'Nome do Prato', 
  'Pedidos':'Pedidos', 
  'Pedido executado pelo cliente':'Pedido executado pelo cliente', 
  'Pontos':'Pontos', 
  'Pontuação':'Pontuação', 
  'Preco':'Preco', 
  'Valor':'Valor', 
  'Pronto':'Pronto', 
  'Qtde':'Qtde', 
  'Quantidade':'Quantidade', 
  //'Quantidade':'Quantidade', 
  'Sabores':'Sabores', 
  'Sabores de Cardápio':'Sabores de Cardápio', 
  'Sequência':'Sequência', 
  //'Codigo':'Codigo', 
  'Sintético por Data':'Sintético por Data', 
  'Sintético por Lanche':'Sintético por Lanche', 
  'Status':'Status', 
  'Status do Pedido':'Status do Pedido', 
  'Subtotal':'Subtotal', 
  'SutTotal':'SutTotal', 
  'Tipo Pagto.':'Tipo Pagto.', 
  'Tipo do Pagamento':'Tipo do Pagamento', 
  'Total':'Total', 
  'Total do Pedido':'Total do Pedido', 
  'Usar Bonificação':'Usar Bonificação', 
  'Usar Bonificação pontuação de Compras':'Usar Bonificação pontuação de Compras', 
  //'Valor':'Valor', 
  'Valor do Prato':'Valor do Prato', 
  'Valor Adicional':'Valor Adicional', 
  'Valor adicional do Sabor ':'Valor adicional do Sabor ', 
  'Vendedores':'Vendedores', 
  'Vendedor':'Vendedor', 
  'Sistema para Pedidos Gastronomicos':'Sistema para Pedidos Gastronomicos', 
};
