export const LANG_EN_NAME = 'en'; 
export const LANG_EN_TRANS = { 
  'USUÁRIO':'USER', 
  'CONSULTAR':'SEARCH', 
  'Consultar':'Search', 
  'EDITAR':'EDIT', 
  'INSERIR':'INSERIR', 
  'Relatórios':'Reports', 
  'Usuários':'Users', 
  'Cadastros':'Records', 
  'RELATÓRIO':'REPORT', 
  'Itens':'Items', 
  'apontamentos':'Releases', 
  'Permissões':'Permissions', 
  'Grupo de Usuários':'User group', 
  'Administração':'Management', 
  'Dicionário':'Dictionary', 
  'CÓDIGO':'ID', 
 'GRUPO':'GROUP', 
 'BEM VINDO AO SISTEMA':'WELCOME TO THE SYSTEM', 
 'é obrigatório':'is required', 
 'Relatório':'Report', 
 'RELATÓRIO DE':'REPORT OF', 
 'FILTRO RELATÓRIO':'FILTER REPORT', 
 'APONTAMENTO DE TEMPOS':'RELEASE OF TIME', 
 'FILTRO APONTAMENTO':'FILTER RELEASE', 
  'cadastro de':'Registration of', 
  'APONTAMENTO DE TEMPO':'RELEASE OF TIME', 
  'Adicionar':'Add',
  'Gravar':'Save',
  'Cancelar':'Cancel',
  'Excluir':'Delete', 
  'Editar':'Edit', 
  'CAMPOS':'FIELDS', 
  'TOTAL GERAL':'GRAND TOTAL', 
  'Gráficos':'Charts', 
  'Imprimir':'Print', 
  'Voltar':'Back', 
  'PIZZA':'PIE', 
  'LINHAS':'LINES', 
  'BARRAS':'BAR', 
  'DE':'FROM', 
  'ATÉ':'TO', 
  'ENTRAR':'ENTER', 
  'ACESSAR':'ACCESS', 
  'LOGIN':'USER', 
  'SENHA':'PASSWORD', 
 'Yumy Foods':'Yumy Foods', 
  'Ativo':'Active', 
  'Cadastro Ativo':'Record Active', 
  'Bonificação':'Bonus for Purchases', 
  'Bonificação por Compras':'Bonus for Purchases', 
  'Cardápio':'Menu', 
  'Cardapio':'Menu', 
  'Categoria':'Category', 
  'Categorias':'Category', 
  'Codigo':'Category', 
  'Código':'ID', 
  'Código de Bonificação':'ID of null', 
  'CheckList Pedidos':'', 
  'Lista de Pedidos':'', 
  'Complemento':'add info', 
  'Complemento do Endereço':'add Info adrress', 
  'Data/Hora':'Date Concluded', 
  'Data e Hora do Pedido':'Date/Hour Concluded Order', 
  'Data/Hora Entregue':'Date/Hour Delivery', 
  'Data/Hora que o pedido foi entregue':'Date/Hour Delivery', 
  'Data/Hora Retirado':'Date/Hour withdrawn', 
  'Data/Hora que saiu para Entrega':'Date/Hour withdrawn', 
  'Descrição':'Description', 
  'Descrição do Prato':'Description', 
  'Estoque':'Stoke', 
  'Estoque do Produto':'Stoke of Product', 
  'Fone':'Phone', 
  'Telefone de Contato':'Contact Phone', 
  'Forma Pgto.':'Form Payment', 
  'Forma de Pagamento':'Form of payment', 
  'Imagem':'Image', 
  'Imagem do Prato':'Image', 
  'Informações Adicionais/Observações':'Obs', 
  'Informações adicionas e Observações':'Address Obs', 
  //'Lista de Pedidos':'', 
  'Número':'Number', 
  'Número(Endereço)':'Number of Address', 
  'Nome':'Name', 
  'Nome do Prato':'Name', 
  'Pedidos':'Orders', 
  'Pedido executado pelo cliente':'Order of Custumer', 
  'Pontos':'Points', 
  'Pontuação':'Points', 
  'Preco':'Price', 
  'Valor':'Price', 
  'Pronto':'', 
  'Qtde':'Amount', 
  'Quantidade':'Amount', 
  //'Quantidade':'', 
  'Sabores':'Flavors', 
  'Sabores de Cardápio':'Flavors of Menu', 
  'Sequência':'Sequence ID', 
  //'Codigo':'Sequence', 
  'Sintético por Data':'Synthetic by date', 
  'Sintético por Lanche':'', 
  'Status':'Status', 
  'Status do Pedido':'Status of Order', 
  'Subtotal':'Subtotal', 
  'SutTotal':'SubTotal', 
  'Tipo Pagto.':'Type of Payment', 
  'Tipo do Pagamento':'Type of Payment', 
  'Total':'Total', 
  'Total do Pedido':'Total of Order', 
  'Usar Bonificação':'Use Bonus', 
  'Usar Bonificação pontuação de Compras':'Use Bonus of Bay', 
  //'Valor':'Amount', 
  'Valor do Prato':'Amount', 
  'Valor Adicional':'Additional value', 
  'Valor adicional do Sabor ':'Additional value', 
  'Vendedores':'Description', 
  'Vendedor':'Descript', 
  'Sistema para Pedidos Gastronomicos':'Food Ordering System', 
};
